version: "3.7"

services:
  postgres:
    image:  postgres
    container_name: challengeDB
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=facile
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: challengeNODE
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local
